---
description: |
  Uses the cimg/python convenience image, which has the prerequisites for installing Cloudsmith's CLI.
parameters:
  tag:
    type: string
    default: "3.12"
    description: >-
      Pick a specific cimg/python image version tag:
      https://circleci.com/developer/images/image/cimg/python
docker:
  - image: cimg/python:<<parameters.tag>>
